name       : time
version    : 1.8
release    : 3
source     :
    - https://ftp.gnu.org/gnu/time/time-1.8.tar.gz : 8a2f540155961a35ba9b84aec5e77e3ae36c74cecb4484db455960601b7a2e1b
homepage   : https://www.gnu.org/software/time
license    : GPL-3.0
component  : system.base
summary    : time (Measure CPU/Memory resource other programs use)
description: |
    time is used with other programs to measure the system resources they use.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
