name       : time
version    : '1.9'
release    : 4
source     :
    - https://ftp.gnu.org/gnu/time/time-1.9.tar.gz : fbacf0c81e62429df3e33bda4cee38756604f18e01d977338e23306a3e3b521e
homepage   : https://www.gnu.org/software/time
license    : GPL-3.0
component  : system.base
summary    : time (Measure CPU/Memory resource other programs use)
description: |
    time is used with other programs to measure the system resources they use.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
