name        : time
version     : 1.7
release     : 2
source      :
    - http://ftp.gnu.org/gnu/time/time-1.7.tar.gz : e37ea79a253bf85a85ada2f7c632c14e481a5fd262a362f6f4fd58e68601496d
homepage    : http://www.gnu.org/software/time
license     :
    - GPL-3.0
summary     : time (Measure CPU/Memory resource other programs use)
description : |
    time is used with other programs to measure the system resources they use.
setup      : |
    ./configure --prefix=/usr --datadir=/usr/share --infodir=/usr/share/info
build      : |
    %make
install    : |
    %make_install prefix=$installdir/usr infodir=$installdir/usr/share/info
